Apps/V1CoreApp/urls.py
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required
from . import views


app_name = 'V1CoreApp'


urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
    path('obesity-overweight-children/', views.US11View.as_view(), name='US11'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile-child/', views.ProfileChildView.as_view(), name='profile-child'),
    path('food-additives/', views.US13View.as_view(), name='US13'),
    path('nutrition-guideline/', views.US21View.as_view(), name='US21'),
    path('US22/', views.US22View.as_view(), name='US22'),
    path('tracker-reminder/', views.US23View.as_view(), name='US23'),
    path('recipe-nutrition-analysis/', views.GuestTrackerView.as_view(), name='guest_tracker'),
    path('about-us/', views.AboutUsView.as_view(), name='about'),
    path('login/', views.Login_RegisterView.as_view(), name='login_or_register'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('dash/', views.US11DashboardView.as_view(), name='dash'),
    path('profile-dashboard/', views.US121View.as_view(), name='US121'),
    path('coming-soon/', views.ComingView.as_view(), name='coming'),
    # import data views
    path('data/', views.ImportDataView.as_view(), name='import_data'),
    # /data/?file_name=pb_who_bmi.csv&model_name=PB_WHO_BMI
]

SunSmart/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    #path("admin/", admin.site.urls),
    path("", include('Apps.CoreApp.urls')),
    #path("user/", include('Apps.UserAuthentication.urls')),
    path("iteration1/", include('Apps.V1CoreApp.urls')),
    path("iteration2/", include('Apps.V2CoreApp.urls'))
]

Apps/V1CoreApp/models.py
from django.db import models

# Create your models here.
GENDER_TYPE = [
    ("M", "Male"),
    ("F", "Female"),
    ("P", "Persons")
]

AGE_GROUP = [
    ("A", "2-3"),
    ("B", "4-8"),
    ("C", "9-13")
]


class PB_AU_CONCERN_V1(models.Model):
    concern = models.CharField(max_length=150, null=True, blank=True)
    gender = models.CharField(max_length=20, choices = GENDER_TYPE, null=True, blank=True)
    age_group = models.CharField(max_length=20, choices = AGE_GROUP, null=True, blank=True)
    percentage = models.FloatField(null=True, blank=True)
    
class PB_WHO_BMI_V1(models.Model):
    bmi = models.CharField(max_length=150, null=True, blank=True)
    year = models.IntegerField( null=True, blank=True)
    gender = models.CharField(max_length=20, choices = GENDER_TYPE, null=True, blank=True)
    crude_estimate = models.FloatField(null=True, blank=True)

Apps/V1CoreApp/views.py
from typing import Any
from django.http.request import HttpRequest as HttpRequest
from django.shortcuts import render, redirect
from django.contrib import messages
from django.http import HttpResponse, JsonResponse
from django.views import generic
from django.core.mail import send_mail
from django.core.management.utils import get_random_secret_key
from .models import *
from django.apps import apps
import os
from .utils import api_request, login_required
import pandas as pd
from django.core import serializers
import json
import requests


class CustomLoginRequiredMixin:
    def dispatch(self, request, *args, **kwargs):
        if 'user_id' not in request.session:
            # Redirect to the login page
            messages.add_message(self.request, messages.INFO, 'You need to login to access the content')
            # Store the requested URL in the session
            request.session['next'] = request.get_full_path()
            return redirect('V1CoreApp:login_or_register')
        return super().dispatch(request, *args, **kwargs)
    
    
class HomeView(generic.TemplateView):
    template_name = 'V1CoreApp/index.html'
    
    def import_data(self):
        filename = "C:/Users/Parisa/Downloads/tb_concern.csv"
        df = pd.read_csv(filename)
        for index, row in df.iterrows():
            temp_row = PB_AU_CONCERN_V1(concern=row['concern'], 
                                        gender=row['gender'],
                                        age_group=row['age_group'],
                                        percentage=row['percentage'])
            
            temp_row.save()
    
    def import_bmi_data(self):
        filename = "C:/Users/Parisa/Downloads/pb_who_bmi.csv"
        df = pd.read_csv(filename)
        for index, row in df.iterrows():
            temp_row = PB_WHO_BMI_V1(bmi=row['bmi_code'], 
                                        gender=row['gender'],
                                        year=row['year'],
                                        crude_estimate=row['crude_estimate'])
            
            temp_row.save()
        
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        
        # self.import_bmi_data()
            
        return super().get_context_data(**kwargs)

#overweight info page    
class US11View(generic.TemplateView):
    template_name = 'V1CoreApp/us11.html'
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        super().get_context_data(**kwargs)
        
        # query from table
        all_data = PB_AU_CONCERN_V1.objects.all()
        serialized_data = serializers.serialize('json', all_data)
        
        
        all_data_bmi = PB_WHO_BMI_V1.objects.all()
        serialized_data_bmi = serializers.serialize('json', all_data_bmi)
    
        
        new_context = {'main_title': 'Obesity and Overweight among Children',
                    #    'sub_title': 'Obesity and Overweight among Children',
                       'page_name': 'Obesity and Overweight',
                       'json_data': serialized_data,
                       'json_data_bmi': serialized_data_bmi}
        
        return new_context
        

class US11DashboardView(generic.TemplateView):
    template_name = 'V1CoreApp/us11_dashboard.html'
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        super().get_context_data(**kwargs)
        
        # query from table
        all_data = PB_AU_CONCERN_V1.objects.all()
        serialized_data = serializers.serialize('json', all_data)
        
        
        all_data_bmi = PB_WHO_BMI_V1.objects.all()
        serialized_data_bmi = serializers.serialize('json', all_data_bmi)
    
        
        new_context = {'main_title': 'Checkout',
                       'sub_title': 'Shop',
                       'page_name': 'US11',
                       'json_data': serialized_data,
                       'json_data_bmi': serialized_data_bmi}
        
        return new_context


class ProfileView(CustomLoginRequiredMixin, generic.TemplateView):
    template_name = 'V1CoreApp/profile.html'
    recipes = None  
    
    def setup(self, request, *args, **kwargs):
        file_address = os.path.join('Data Sources', 'recipes.json')
        with open(file_address, 'r') as f:
            # JSON to dictionary
            self.recipes = json.load(f)
        return super().setup(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        
        new_context = {'main_title': 'Profile',
                    #    'sub_title': 'Obesity and Overweight among Children',
                       'page_name': 'Profile',
                       'recipes': self.recipes
                       }
        return new_context
    
    
class ProfileChildView(CustomLoginRequiredMixin, generic.TemplateView):
    template_name = 'V1CoreApp/profile_child.html'
    recipes = None  
    
    def setup(self, request, *args, **kwargs):
        file_address = os.path.join('Data Sources', 'recipes.json')
        with open(file_address, 'r') as f:
            # JSON to dictionary
            self.recipes = json.load(f)
        return super().setup(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        
        new_context = {'main_title': "Child's Profile",
                    #    'sub_title': 'Obesity and Overweight among Children',
                       'page_name': "Child's Profile",
                       'recipes': self.recipes
                       }
        return new_context
  
    
class US121View(generic.TemplateView):
    template_name = 'V1CoreApp/us121.html'


class US13View(generic.TemplateView):
    template_name = 'V1CoreApp/additive.html'
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        super().get_context_data(**kwargs)
        
        
    
        
        new_context = {'main_title': 'Understanding Food Additives: Uses, Reactions, and Safety',
                       'sub_title': '',
                       'page_name': 'Understanding Food Additives'
                       }
        
        return new_context

#nutrition-guideline
class US21View(generic.TemplateView):
    template_name = 'V1CoreApp/nutrition-guideline.html'
    data = ""
    
    #read json guideline
    def setup(self, request, *args, **kwargs):
        file_address = os.path.join('Data Sources', 'guideline.json')
        with open(file_address, 'r') as f:
            # JSON to dictionary
            self.data = json.load(f)
            
        return super().setup(request, *args, **kwargs)
    
    #search age
    def post(self, request):
        selected_age_range = request.POST.get('selected_age_range')  
        print(selected_age_range) 
        # find the recipe in recipes
        for r in self.data:
            if r.get('age_range') == selected_age_range:
                age_range = r
                print(age_range)
                break
            else:
                age_range = {'status': 'not found'}
                
        return JsonResponse(age_range)            
              
                
class US22View(generic.TemplateView):
    template_name = 'V1CoreApp/us22.html'

#Reminder page
class US23View(generic.TemplateView):
    template_name = 'V1CoreApp/reminder_main.html'
    def post(self, request):
        submit_data = request.POST.get('submit_data', None)
        messages.add_message(self.request, messages.SUCCESS, 'The information saved successfully')
        return redirect('V1CoreApp:US23')
        
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        super().get_context_data(**kwargs)
  
        new_context = {'main_title': 'Reminder',
                    #    'sub_title': 'Obesity and Overweight among Children',
                       'page_name': 'Reminder'
        }
        
        return new_context

class AboutUsView(generic.TemplateView):
    template_name = 'V1CoreApp/about_us.html'


# class GuestTrackerView(CustomLoginRequiredMixin, generic.TemplateView):
class GuestTrackerView(generic.TemplateView):
    template_name = 'V1CoreApp/Nutrition_Analysis.html'
    recipes = None
    headers = {
                "Content-Type": "application/json"
                }
    
    def setup(self, request, *args, **kwargs):
        file_address = os.path.join('Data Sources', 'recipes.json')
        with open(file_address, 'r') as f:
            # JSON to dictionary
            self.recipes = json.load(f)
            
        return super().setup(request, *args, **kwargs)
    
    def post(self, request):
        
        if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            selected_recipe = request.POST.get('selected_recipe')
            recipe_intake = request.POST.get('recipe_intake')
                            
            # find the recipe in recipes
            for r in self.recipes:
                if r.get('recipe_name') == selected_recipe:
                    recipe = r
                    break
                else:
                    recipe = {'status': 'not found'}
                    
            # send sign-in data to authentication API
            api_url = 'https://juniorjoy.site/api/api/calcucalories'
            data = {
                "query": recipe['recipe_ingredients'],
                "intake": recipe_intake,
                "serving": recipe['recipe_servings']
            }
                        
            response = requests.get(api_url, headers=self.headers, json=data)
            
            if response.status_code == 200:
                # Append the calorie information to the recipe
                recipe['nutrient_info'] = response.json()            
                response_data = response.json()

                recipe['calories_intake'] = response_data['calories_intake']
                recipe['serving_size_g_intake'] = response_data['serving_size_g_intake']

Apps/V1CoreApp/templates/V1CoreApp/Nutrition_Analysis.html
{% extends "V1CoreApp/base.html" %}
{% load static %}


{% block title_block %}
    
{% endblock title_block %}





{% block main_content %}

<div class="container">
    <div class="page-header" style=" background-color:#d2efd5; text-align: center;">
        <div class="container">
            <h1 class="page-title col-lg-10 mx-auto" style="font-size: 24px;text-align: center;">Nutrition Analyzer<span>{{sub_title}}</span></h1>
        </div><!-- End .container -->
</div>

<nav aria-label="breadcrumb" class="breadcrumb-nav border-0 mb-0">
    <div class="container">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url "V1CoreApp:index" %}">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Nutrition Analyzer</li>
        </ol>
    </div><!-- End .container -->
</nav><!-- End .breadcrumb-nav -->

<div class="page-content">
    <div class="checkout">
        <div class="container">
        {% include "V1CoreApp/components/recipe_analysis.html" %}
        </div>
    </div>
</div>



<div class="container">
    <div class="cta cta-border mb-5">
        <div class="row justify-content-center">
            <div class="col-md-11 col-xl-10">
                <div class="cta-content">
                    <div class="cta-heading">
                        <h3 class="cta-title text-center">Curious about your child's nutritional needs?</h3><!-- End .cta-title -->
                    </div><!-- End .cta-heading -->
                    
                    <div class="cta-text">
                        <p> After analyzing their meal with our Nutrition Analyzer, head over to Australian Nutrition Age-Based Guidelines for personalized recommendations. View Guidelines to ensure your child's diet is perfectly balanced for their growth and development!  </p>
                    </div><!-- End .cta-text -->
                    <a href="{% url "V1CoreApp:US21" %}" class="btn btn-primary btn-rounded"><span>Nutrition Guidelines</span><i class="icon-long-arrow-right"></i></a>
                </div><!-- End .cta-content -->
            </div><!-- End .col-xl-7 -->
        </div><!-- End .row -->
    </div><!-- End .cta -->
 
</div>

{% endblock main_content %}


{% block more_script %}
<script>
    $(document).ready(function () {
        $('#recipe, #intake').on('input', function (e) {
            var recipeChoice = $('#recipe').val(); // Get selected value
            var recipeIntake = $('#intake').val(); // Get selected value

            if (recipeChoice === 'nan') {
                return; // Do nothing and exit the function
            };
            // AJAX call
            $.ajax({
                type: "POST",
                url: "{% url 'V1CoreApp:guest_tracker' %}", 
                data: {'selected_recipe': recipeChoice,
                        'recipe_intake': recipeIntake,
                        'csrfmiddlewaretoken': '{{csrf_token}}'
                        },
                dataType: 'json',
                success: function (response) {
                    // Update with the received JSON data
                    //console.log(response);
                    if(response.status == 'not found'){
                        $('#recipe_description').empty();
                    } else {
                    $('#recipe_description').text(response.recipe_instructions);
                    $('.table-summary tbody').empty().append(
                        '<tr><td>Calories:</td><td>' + response.calories_intake+ 'Kcal'+
                        '<tr><td>Total Fat:</td><td>' + response.fat_total_g_intake+ 'g'+
                        '<tr><td>Saturated Fat:</td><td>' + response.fat_saturated_g_intake+ 'g'+
                        '<tr><td>Carbohydrates:</td><td>' + response.carbohydrates_total_g_intake+ 'g'+
                        '<tr><td>Protein: </td><td>' + response.protein_g_intake+ 'g'+
                        '<tr><td>Fiber:</td><td>' + response.fiber_g_intake+ 'g'
                    );
                    }
                },
                error: function (request, status, error) {
                    console.log(request.status + ": " + request.responseText);
                }
            });
        });
    });
</script>
{% endblock more_script %}

Apps/V1CoreApp/templates/V1CoreApp/index.html
{% extends "V1CoreApp/base.html" %}
{% load static %}

{% block title_block %}
<title>Home Page</title>
{% endblock title_block %}



{% block main_content %}

<!-- Section 1 Slider Section -->
<div class="intro-section">
    <div class="intro-section-slider">
        <div class="container">
            <div class="intro-slider-container slider-container-ratio mb-0">
                <div class="intro-slider owl-carousel owl-simple owl-light" data-toggle="owl" 
                    data-owl-options='{
                        "nav": false, 
                        "dots": true,
                        "responsive": {
                            "1200": {
                                "nav": true,
                                "dots": false
                            }
                        }
                    }'>
                    <div class="intro-slide">
                        <figure class="slide-image">
                            <picture>
                                <source media="(max-width: 480px)" srcset="{% static "assets/images/banners/banner1-480w.jpg" %}">
                                <img src="{% static "assets/images/banners/banner1.jpg" %}" alt="Image Desc">
                            </picture>
                        </figure><!-- End .slide-image -->

                        <div class="intro-content">
                            
                            <h2 class="intro-title text-white">JuniorJoy <br></h2><!-- End .intro-title -->
                            <h3 class="intro-subtitle">Food For Health Joy For Life<br><br>Curious about your child's nutritional needs?</h3>
                            <!-- <h2 class="intro-title text-white">Anaylze your children's nurtrion needs today! <br></h2> -->
                            
                            
                            <!-- <h3 class="intro-subtitle col-md-8">Encouraging children to prioritise nutritious foods for a healthy and vibrant life, emphasising the connection between good nutrition and overall well-being.</h3>End .h3 intro-subtitle -->
                            <a href="{% url "V1CoreApp:guest_tracker" %}" class="btn btn-primary">

                                <span>ANALYZE NOW</span>
                            </a>


                        </div><!-- End .intro-content -->
                    </div><!-- End .intro-slide -->

                    <div class="intro-slide">
                        <figure class="slide-image">
                            <picture>
                                <source media="(max-width: 480px)" srcset="{% static "assets/images/banners/banner3-480w.jpg" %}">
                                <img src="{% static "assets/images/banners/banner3.jpg" %}" alt="Image Desc">
                            </picture>
                        </figure><!-- End .slide-image -->

                        <div class="intro-content">
                            <h2 class="intro-title text-white">JuniorJoy <br></h2><!-- End .intro-title -->
                            <h3 class="intro-subtitle">Do you want to know about <br><br>your children's nutritional needs?</h3>
                            <!-- <h3 class="intro-subtitle text-primary">Explore our curated collection of nutritious meals for children.</h3> End .h3 intro-subtitle -->
                            <!-- <h2 class="intro-title text-primary">Nurturing <br> Your Child's Health <br> Every Step of the Way</h2> -->
                            <!-- <h2 class="intro-title text-primary">Explore our curated collection of nutritious meals for children. -->
                            </h2> <!-- End .intro-title-->

                            <a href="{% url "V1CoreApp:US21" %}" class="btn btn-primary">
                                <span>DISCOVER NOW</span>
                            </a>
                        </div><!-- End .intro-content -->
                    </div><!-- End .intro-slide -->

                    <div class="intro-slide">
                        <figure class="slide-image">
                            <picture>
                                <source media="(max-width: 480px)" srcset="{% static "assets/images/banners/banner2-480w.jpg" %}">
                                <img src="{% static "assets/images/banners/banner2.jpg" %}" alt="Image Desc">
                            </picture>
                        </figure><!-- End .slide-image -->

                        <div class="intro-content">
                            <h2 class="intro-title text-white">JuniorJoy <br></h2><!-- End .intro-title -->
                            <h3 class="intro-subtitle">Explore our curated <br><br> collection of nutritious <br> <br>meals for children</h3>
                            
                            <!-- <h2 class="intro-title text-white">Explore our curated <br> collection of nutritious <br> meals for children</h2>End .intro-title -->
                            <!-- <h2 class="intro-subtitle ">Every day as a parent is a chance to inspire, nurture, <br> and shape the incredible future of your child. -->
                            </h2><!-- End .h3 intro-subtitle -->
                            

                            <div class="intro-text text-white"> 
                            </div><!-- End .intro-text -->

                            <a href="{% url "V1CoreApp:US13" %}" class="btn btn-primary">
                                <span>LEARN MORE</span>
                            </a>
                             
                        </div><!-- End .intro-content -->
                    </div><!-- End .intro-slide -->
                </div><!-- End .intro-slider owl-carousel owl-simple -->
                        
                <span class="slider-loader"></span><!-- End .slider-loader -->
            </div><!-- End .intro-slider-container -->
        </div><!-- End .container -->
    </div><!-- End .intro-section-slider -->


</div><!-- End .intro-section -->
<!-- End Section 1 Slider Section -->


<!-- section2 obesity -->
<div class="container">
 
    <hr class="mb-2">
    <div class="cta bg-image pt-3 pb-3 mb-3" style="background-color:#d2efd5;background-position: center right;">
        <div class="row justify-content-center">
            <div class="col-sm-10 col-md-8 col-lg-8">
                <div class="cta-text text-center">
                    <h3 class="cta-title">Combatting Childhood Overweight Starts with You</h3><!-- End .cta-title -->
                    <p class="cta-desc"><p>In Australia, the prevalence of overweight and obesity among children is a growing concern. Explore the alarming trend and discover actionable tips from experts on how to address this issue.
                    </p><!-- End .cta-desc -->
            
                    <a href="{% url "V1CoreApp:US11" %}" class="btn btn-primary btn-rounded"><span>Explore More</span><i class="icon-long-arrow-right"></i></a>
                </div><!-- End .cta-text -->
            </div><!-- End .col-sm-10 col-md-8 col-lg-6 -->
        </div><!-- End .row -->
    </div><!-- End .cta -->

</div>





<!-- Section 3 action banners -->
<div class="pt-3 pb-3">
  <div class="container">
      <div class="banner-group">
          <div class="row">
              <div class="col-sm-6 col-lg-4">
                  <div class="banner banner-overlay banner-lg">
                          <img src="{% static "assets/images/banners/US12-1.jpg" %}" alt="Banner">
                      <div class="banner-content banner-content-bottom">
                          <h4 class="banner-subtitle text-white">Check Nutritions of your Child’s portion</a></h4><!-- End .banner-subtitle -->
                          <h3 class="banner-title text-white">Are you mindful of your <br> child's daily plate count?</a></h3><!-- End .banner-title -->
                          
                          <a href="{% url "V1CoreApp:guest_tracker" %}" class="btn btn-outline-white banner-link">Analyze Portion</a>
                      </div><!-- End .banner-content -->
                  </div><!-- End .banner -->
              </div><!-- End .col-lg-4 -->
              <div class="col-sm-6 col-lg-4">
                <div class="banner banner-overlay banner-lg">
                        <img src="{% static "assets/images/banners/US11.jpg" %}" alt="Banner">
                    <div class="banner-content banner-content-bottom">
                        <h4 class="banner-subtitle text-white">Nutrition Needs Based On Your <br>Child’s Profile</a></h4><!-- End .banner-subtitle -->
                        <h3 class="banner-title text-white">Are you meeting your child's<br> nutritional needs?</a></h3><!-- End .banner-title -->
                        <!-- <div class="banner-text text-white">Ready to record daily routine to build your child’s dietary plan?</a></div><!-- End .banner-text -->
                        <a href="{% url "V1CoreApp:US21" %}" class="btn btn-outline-white banner-link">Discover Now</a>
                    </div><!-- End .banner-content -->
                </div><!-- End .banner -->
            </div><!-- End .col-lg-4 -->
            <div class="col-sm-6 col-lg-4">
                <div class="banner banner-overlay banner-lg">
                        <img src="{% static "assets/images/banners/US21.jpg" %}" alt="Banner">
                    <div class="banner-content banner-content-bottom">
                        <h4 class="banner-subtitle text-white">Additive Awareness of Parents</a></h4><!-- End .banner-subtitle -->
                        <h3 class="banner-title text-white">What do you know about <br>food Additives?</a></h3><!-- End .banner-title -->
                        <!--<div class="banner-text text-white">from $19.00</a></div><!-- End .banner-text -->
                        <a href="{% url "V1CoreApp:US13" %}" class="btn btn-outline-white banner-link">Learn More</a>
                    </div><!-- End .banner-content -->
                </div><!-- End .banner -->
            </div><!-- End .col-lg-4 -->
          </div><!-- End .row -->
      </div><!-- End .banner-group -->

  </div><!-- End .container -->
</div><!-- End .bg-lighter -->
<!-- End Section 3 action banners -->

<!-- section4 -->
<div class="container">
    <div class="cta cta-border mb-5">
        <div class="row justify-content-center">
            <div class="col-md-11 col-xl-10">
                <div class="cta-content">
                    <div class="cta-heading">
                        <h3 class="cta-title text-center">Food  <br> For Health<br>Joy For Life.</h3><!-- End .cta-title -->
                    </div><!-- End .cta-heading -->
                    
                    <div class="cta-text">
                        <p>Embrace the journey of nurturing your child's health with JuniorJoy, where every small step you take today paves the way for a brighter, healthier future tomorrow.</p>
                    </div><!-- End .cta-text -->
                    <!-- <a href="#" class="btn btn-primary btn-rounded"><span>Click Here</span><i class="icon-long-arrow-right"></i></a> -->
                </div><!-- End .cta-content -->
            </div><!-- End .col-xl-7 -->
        </div><!-- End .row -->
    </div><!-- End .cta -->
 
</div>

<!-- Section 5 small action banners -->
<div class="container">
    <div class="row justify-content-center">
        <div class="col-sm-6 col-md-4">
            <div class="banner banner-cat">
                    <img src="{% static "assets/images/banners/footerus12.jpg" %}" alt="Banner">
                <div class="banner-content banner-content-overlay text-center">
                    <h3 class="banner-title font-weight-normal">Nutrition Analyzer</h3><!-- End .banner-title -->
                    <h4 class="banner-subtitle">Analyze Your children's Diet</h4><!-- End .banner-subtitle -->
                    <a href="{% url "V1CoreApp:guest_tracker" %}" class="banner-link">Explore More</a>
                </div><!-- End .banner-content -->
            </div><!-- End .banner -->
        </div><!-- End .col-md-4 -->




        <!-- This is the "Nutrition Analysis Tool" function -->
        <!-- <div class="col-sm-6 col-md-4">
            <div class="banner banner-cat">
                    <img src="{% static "assets/images/banners/footerus13.jpg" %}" alt="Banner">
                <div class="banner-content banner-content-overlay text-center">
                    <h3 class="banner-title font-weight-normal">Nutrition Analysis Tool</h3>End .banner-title -->
                    <!-- <h4 class="banner-subtitle">Get insight into your children's diet</h4>End .banner-subtitle -->
                    <!-- <a href="{% url "V1CoreApp:guest_tracker" %}" class="banner-link">Explore More</a> -->
                <!-- </div>End .banner-content -->
            <!-- </div>End .banner -->
        <!-- </div>End .col-md-4 -->



        <div class="col-sm-6 col-md-4">
            <div class="banner banner-cat">
                    <img src="{% static "assets/images/banners/footerus11.jpg" %}" alt="Banner">
                <div class="banner-content banner-content-overlay text-center">
                    <h3 class="banner-title font-weight-normal">Set Reminders</h3>
                    <!-- End .banner-title -->
                    <h4 class="banner-subtitle">Effortless Mealtime Scheduling</h4>
                    <!-- End .banner-subtitle -->
                    <a href="{% url "V1CoreApp:US23" %}" class="banner-link">Set Now</a>
                </div>
                <!-- End .banner-content -->
            </div>
            <!-- End .banner -->
       </div>
       <!-- End .col-md-4 -->
    </div><!-- End .row -->
</div>
<!-- End Section 5 small action banners -->


{% endblock main_content %}

Apps/V1CoreApp/templates/V1CoreApp/us22.html
{% extends "V1CoreApp/base.html" %}
{% load static %}


{% block title_block %}
    US 11
{% endblock title_block %}





{% block main_content %}
    <div class="w3-content" style="max-width:2000px;margin-top:46px">
        <h1> Page US22</h1>
    </div>

    
{% endblock main_content %}