Apps/CoreApp/urls.py
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required
from .views import RecipeDetailView, RecipeListView
from . import views



app_name = 'CoreApp'


urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
    path('obesity-overweight-children/', views.US11View.as_view(), name='US11'),
    path('food-additives/', views.US13View.as_view(), name='US13'),
    path('nutrition-guideline/', views.US21View.as_view(), name='US21'),
    path('tracker-reminder/', views.ReminderView.as_view(), name='US23'),
    path('recipe-nutrition-analysis/', views.GuestTrackerView.as_view(), name='guest_tracker'),
    path('about-us/', views.AboutUsView.as_view(), name='about'),
    path('dash/', views.US11DashboardView.as_view(), name='dash'),
    path('coming-soon/', views.ComingView.as_view(), name='coming'),
    path('macronutrients-children/', views.MacronutrientsView.as_view(), name='macronutrients'),
    path('micronutrients-children/', views.MicronutrientsView.as_view(), name='micronutrients'),
    path('bmi-calculator/', views.BmiCalculatorView.as_view(), name='bmi_calculator'),
    # path('recipe/', views.RecipeView.as_view(), name='recipe'),
    path('recipes/', views.RecipeListView.as_view(), name='recipes'),
    path("recipes/<slug:slug>/", RecipeDetailView.as_view(), name="recipe-detail"),
    path('veggie-insights/', views.VeggiView.as_view(), name='Veggi'),
    path('custom-recipe-analysis/', views.OuterRecipeAnalysisView.as_view(), name='outer_recipe_analysis'),
    path('sugar-insights/',  views.SugarView.as_view(), name='sugar_insights'),
    
    path('dietary-awareness/',  views.DietAwarenessView.as_view(), name='dietary_awareness'),
    
    # import data views
    #path('data/', views.ImportDataView.as_view(), name='import_data'),
    path('rr/', views.LoadRecipesDataView.as_view()),
    path('ee/', views.ExtractDataView.as_view()),
    # /data/?file_name=pb_who_bmi.csv&model_name=PB_WHO_BMI
    
    
]

SunSmart/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    #path("admin/", admin.site.urls),
    path("", include('Apps.CoreApp.urls')),
    #path("user/", include('Apps.UserAuthentication.urls')),
    path("iteration1/", include('Apps.V1CoreApp.urls')),
    path("iteration2/", include('Apps.V2CoreApp.urls'))
]

Apps/CoreApp/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
import numpy

GENDER_TYPE = [
    ("M", "Male"),
    ("F", "Female"),
    ("P", "Persons")
]

AGE_GROUP = [
    ("A", "2-3"),
    ("B", "4-8"),
    ("C", "9-13")
]


class PB_AU_CONCERN(models.Model):
    concern = models.CharField(max_length=150, null=True, blank=True)
    gender = models.CharField(max_length=20, choices = GENDER_TYPE, null=True, blank=True)
    age_group = models.CharField(max_length=20, choices = AGE_GROUP, null=True, blank=True)
    percentage = models.FloatField(null=True, blank=True)
    
class PB_AU_VEGGIE(models.Model):
    year = models.IntegerField( null=True, blank=True)
    concern = models.CharField(max_length=150, null=True, blank=True)
    concern_label = models.CharField(max_length=150, null=True, blank=True)
    gender = models.CharField(max_length=20, choices = GENDER_TYPE, null=True, blank=True)
    age_group = models.CharField(max_length=20, choices = AGE_GROUP, null=True, blank=True)
    percentage = models.FloatField(null=True, blank=True)
    margin_error = models.FloatField(null=True, blank=True)    
    
class PB_WHO_BMI(models.Model):
    bmi = models.CharField(max_length=150, null=True, blank=True)
    year = models.IntegerField( null=True, blank=True)
    gender = models.CharField(max_length=20, choices = GENDER_TYPE, null=True, blank=True)
    crude_estimate = models.FloatField(null=True, blank=True)
    

class PAGE_VIEW(models.Model):
    path = models.CharField(max_length=1001, unique=True)
    views = models.IntegerField(default=1)
    
class HEALTH_TAG(models.Model):
    tag = models.CharField(max_length=150, null=True, blank=True)


class DIET_LABEL(models.Model):
    label = models.CharField(max_length=150, null=True, blank=True)


class MEAL_TYPE(models.Model):
    type = models.CharField(max_length=150, null=True, blank=True)


class INGREDIENT(models.Model):
    name = models.CharField(max_length=100)
    food_category = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class NUTRIENTS(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class RECIPES(models.Model):
    name = models.CharField(max_length=500, null=True, blank=True)
    description = models.TextField( null=True, blank=True)
    url = models.URLField(max_length=1000)
    total_time = models.CharField(max_length=5, null=True, blank=True)
    serving = models.CharField(max_length=5, null=True, blank=True)
    
    health_tag = models.ManyToManyField(HEALTH_TAG, related_name='recipes_h')
    diet_label = models.ManyToManyField(DIET_LABEL, related_name='recipes_d')
    meal = models.ManyToManyField(MEAL_TYPE, related_name='recipes_m')
    ingredients = models.ManyToManyField(INGREDIENT, through='RECIPE_INGREDIENT')
    nutrients = models.ManyToManyField(NUTRIENTS, through='RECIPE_NUTRIENTS')
    
    slug = models.SlugField(max_length=500, unique=True, null=True, blank=True)
    page_view = models.OneToOneField(PAGE_VIEW, on_delete=models.CASCADE, null=True, blank=True)
    created_on = models.DateTimeField(auto_now_add=True, editable=False)
    

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.slug = slugify(self.name)
        if update_fields is not None and "name" in update_fields:
            update_fields = {"slug"}.union(update_fields)
                          
        # Create or update associated PAGE_VIEW
        if not self.page_view_id:
            page_view, _ = PAGE_VIEW.objects.get_or_create(path=self.get_absolute_url())
            self.page_view = page_view
            
        super().save(
            force_insert=force_insert,
            force_update=force_update,
            using=using,
            update_fields=update_fields,
        )
        
    def get_absolute_url(self):
        # return urllib.parse.unquote(reverse('CoreAPP:recipe-detail', kwargs={'slug': self.slug}))
        return reverse('CoreApp:recipe-detail', kwargs={'slug': self.slug})
        

class RECIPE_INGREDIENT(models.Model):
    recipe = models.ForeignKey(RECIPES, related_name='related_ingredients', on_delete=models.CASCADE)
    ingredient = models.ForeignKey(INGREDIENT, on_delete=models.CASCADE)
    quantity = models.CharField(max_length=100, null=True, blank=True)
    measure = models.CharField(max_length=50, null=True, blank=True)
    ingredient_text = models.CharField(max_length=700, null=True, blank=True)

    def __str__(self):
        return f"{self.quantity} {self.measure} of {self.ingredient.name} for {self.recipe}"
    
class RECIPE_NUTRIENTS(models.Model):
    recipe = models.ForeignKey(RECIPES, related_name='related_nutrients', on_delete=models.CASCADE)
    nutrient = models.ForeignKey(NUTRIENTS, on_delete=models.CASCADE)
    quantity = models.CharField(max_length=100, null=True, blank=True)
    measure = models.CharField(max_length=50, null=True, blank=True)


    def __str__(self):
        return f"{self.nutrient.name} : {numpy.round(float(self.quantity))} {self.measure} "
    


    

Apps/CoreApp/views.py
from typing import Any
from django.http.request import HttpRequest as HttpRequest
from django.shortcuts import render, redirect
from django.urls import reverse
from django.conf import settings
from django.contrib import messages
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.views import generic
from django.core.mail import send_mail
from django.core.management.utils import get_random_secret_key
from django.utils.text import slugify
from .models import *
from django.apps import apps
import os
from .utils import api_request, login_required
import pandas as pd
from django.core import serializers
import json
from . import clustering
import requests
from openai import OpenAI
from django.db.models import Q
from functools import reduce
from operator import or_
import re
from django.utils.safestring import mark_safe


class CustomLoginRequiredMixin:
    def dispatch(self, request, *args, **kwargs):
        if 'user_id' not in request.session:
            # Redirect to the login page
            messages.add_message(self.request, messages.INFO, 'You need to login to access the content')
            # Store the requested URL in the session
            request.session['next'] = request.get_full_path()
            return redirect('CoreApp:login_or_register')
        return super().dispatch(request, *args, **kwargs)
    
    
class HomeView(generic.TemplateView):
    template_name = 'CoreApp/index.html'
    
    def import_data(self):
        filename = "C:/Users/Parisa/Downloads/tb_concern.csv"
        df = pd.read_csv(filename)
        for index, row in df.iterrows():
            temp_row = PB_AU_CONCERN(concern=row['concern'], 
                                        gender=row['gender'],
                                        age_group=row['age_group'],
                                        percentage=row['percentage'])
            
            temp_row.save()
    
    def import_bmi_data(self):
        filename = "C:/Users/Parisa/Downloads/pb_who_bmi.csv"
        df = pd.read_csv(filename)
        for index, row in df.iterrows():
            temp_row = PB_WHO_BMI(bmi=row['bmi_code'], 
                                        gender=row['gender'],
                                        year=row['year'],
                                        crude_estimate=row['crude_estimate'])
            
            temp_row.save()
        
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        
        # self.import_bmi_data()
            
        return super().get_context_data(**kwargs)

#overweight info page    
class US11View(generic.TemplateView):
    template_name = 'CoreApp/overweight.html'
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        super().get_context_data(**kwargs)
        
        # query from table
        all_data = PB_AU_CONCERN.objects.all()
        serialized_data = serializers.serialize('json', all_data)
        
        
        all_data_bmi = PB_WHO_BMI.objects.all()
        serialized_data_bmi = serializers.serialize('json', all_data_bmi)
    
        
        new_context = {'main_title': 'Obesity and Overweight among Children',
                    #    'sub_title': 'Obesity and Overweight among Children',
                       'page_name': 'Obesity and Overweight',
                       'json_data': serialized_data,
                       'json_data_bmi': serialized_data_bmi}
        
        return new_context
        

class US11DashboardView(generic.TemplateView):
    template_name = 'CoreApp/us11_dashboard.html'
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        super().get_context_data(**kwargs)
        
        # query from table
        all_data = PB_AU_CONCERN.objects.all()
        serialized_data = serializers.serialize('json', all_data)
        
        
        all_data_bmi = PB_WHO_BMI.objects.all()
        serialized_data_bmi = serializers.serialize('json', all_data_bmi)
    
        
        new_context = {'main_title': 'Checkout',
                       'sub_title': 'Shop',
                       'page_name': 'US11',
                       'json_data': serialized_data,
                       'json_data_bmi': serialized_data_bmi}
        
        return new_context
 
    
class US121View(generic.TemplateView):
    template_name = 'CoreApp/us121.html'


class US13View(generic.TemplateView):
    template_name = 'CoreApp/additive.html'
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        super().get_context_data(**kwargs)
        
        
    
        
        new_context = {'main_title': 'Understanding Food Additives: Uses, Reactions, and Safety',
                       'sub_title': '',
                       'page_name': 'Understanding Food Additives'
                       }
        
        return new_context

#nutrition-guideline
class US21View(generic.TemplateView):
    template_name = 'CoreApp/nutrition-guideline.html'
    data = ""
    
    #read json guideline
    def setup(self, request, *args, **kwargs):
        file_address = os.path.join('Data Sources', 'guideline.json')
        with open(file_address, 'r') as f:
            # JSON to dictionary
            self.data = json.load(f)
            
        return super().setup(request, *args, **kwargs)
    
    #search age
    def post(self, request):
        selected_age_range = request.POST.get('selected_age_range')  
        print(selected_age_range) 
        # find the recipe in recipes
        for r in self.data:
            if r.get('age_range') == selected_age_range:
                age_range = r
                print(age_range)
                break
            else:
                age_range = {'status': 'not found'}
                
        return JsonResponse(age_range)            
              
                
class US22View(generic.TemplateView):
    template_name = 'CoreApp/us22.html'

#Reminder page
class ReminderView(generic.TemplateView):
    template_name = 'CoreApp/reminder_main.html'
    
    def post(self, request):
        email = request.POST.get('email', None)
        date = request.POST.get('date', None)
        meal = request.POST.get('meal', None)
        
        # send sign-in data to authentication API
        api_url = 'http://juniorjoy.site/api/reminder/set-ses-reminder'
        
        data = {'email': email,
                'date': date,
                'meal': meal
        }
        response = api_request(url=api_url, parameters=data, request_type='POST')    
       
        messages.add_message(self.request, messages.SUCCESS, 'The reminder has been set successfully  ')
        
        return redirect('CoreApp:US23')
        
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        super().get_context_data(**kwargs)
  
        new_context = {'main_title': 'Reminder',
                       'sub_title': '',
                       'page_name': 'Reminder'
        }
        
        return new_context


class AboutUsView(generic.TemplateView):
    template_name = 'CoreApp/about_us.html'


# class GuestTrackerView(CustomLoginRequiredMixin, generic.TemplateView):
class GuestTrackerView(generic.TemplateView):
    template_name = 'CoreApp/Nutrition_Analysis.html'
    recipes = None
    headers = {
                "Content-Type": "application/json"
                }
    
    def setup(self, request, *args, **kwargs):
        file_address = os.path.join('Data Sources', 'recipes.json')
        with open(file_address, 'r') as f:
            # JSON to dictionary
            self.recipes = json.load(f)
            
        return super().setup(request, *args, **kwargs)
    
    def post(self, request):
        
        if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            selected_recipe = request.POST.get('selected_recipe')
            recipe_intake = request.POST.get('recipe_intake')
                            
            # find the recipe in recipes
            for r in self.recipes:
                if r.get('recipe_name') == selected_recipe:
                    recipe = r
                    break
                else:
                    recipe = {'status': 'not found'}
                    
            # send sign-in data to authentication API
            api_url = 'https://juniorjoy.site/api/api/calcucalories'
            data = {
                "query": recipe['recipe_ingredients'],
                "intake": recipe_intake,
                "serving": recipe['recipe_servings']
            }
                        
            response = requests.get(api_url, headers=self.headers, json=data)
            
            if response.status_code == 200:
                # Append the calorie information to the recipe
                recipe['nutrient_info'] = response.json()            
                response_data = response.json()

                recipe['calories_intake'] = response_data['calories_intake']
                recipe['serving_size_g_intake'] = response_data['serving_size_g_intake']
                recipe['fat_total_g_intake'] = response_data['fat_total_g_intake']
                recipe['fat_saturated_g_intake'] = response_data['fat_saturated_g_intake']
                recipe['protein_g_intake'] = response_data['protein_g_intake']
                # recipe['sodium_mg_intake'] = response_data['sodium_mg_intake']
                # recipe['potassium_mg_intake'] = response_data['potassium_mg_intake']
                # recipe['cholesterol_mg_intake'] = response_data['cholesterol_mg_intake']
                recipe['carbohydrates_total_g_intake'] = response_data['carbohydrates_total_g_intake']
                recipe['fiber_g_intake'] = response_data['fiber_g_intake']
                recipe['sugar_g_intake'] = response_data['sugar_g_intake']

            else:
                # Handle API error
                recipe['nutrient_info'] = {'error': 'Failed to retrieve calorie information'}
                    

Apps/CoreApp/templates/CoreApp/Macronutrients.html
{% extends "CoreApp/base.html" %}

{% load static %}

{% block title_block %}
{% endblock title_block %}

{% block extra_css %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<style>
    .tagcloud a {
      padding: 10px 20px;
      border: 0px solid #ccc;
      border-radius: 10px; /* Adjust border radius for rounded corners */
      text-decoration: none;
      color: #000000;
      font-weight: bold;
      background-color:  #d2efd5;
      transition: background-color 0.3s, border-color 0.3s, color 0.3s;
    }

    .tagcloud a:hover {
      background-color: #72dcdc;
      border-color: #000000;
      color: #000000; /* Change text color on hover */
    }
    .food-icon {
      width: 50px;
      height: 50px;
      transition: transform 0.3s ease;
    }
    
    /* Define the hover effect */
    .food-icon:hover {
      transform: scale(1.2); /* Scale up the image on hover */
    }
</style>
{% endblock extra_css %}

{% block main_content %}

{% include "CoreApp/components/breadcrumb.html" %}
<div class="entry-content editor-content" style ='justify-content: center'>
  
  <div style="display: flex; justify-content: center; padding-bottom: 10px;">
    <div class="container col-8">
      <div>
        <h3>What is Macronutrient</h3>
        <p>Macronutrients in food, like carbohydrates, proteins, and fats, are crucial for kids' energy and growth. Carbs, found in bread and fruits, fuel their play. Proteins from meat and beans help build strong muscles. Fats, in avocados and nuts, support brain power. Balancing these nutrients keeps kids healthy and energized for all their activities, ensuring they have the strength and stamina to play, learn, and explore every day.</p>
      </div>

      <div class="row">
        
          <div class="widget pt-2">
            <h3 class="widget-title">How will Macronutrients benefit your children?</h3><!-- End .widget-title -->
            <p >Select the Macronutrients to get more information.</p>
            <div class="tagcloud mb-0" id="tagcloud" style="font-weight: bold;">
              <a name="Carbohydrates">Carbs</a>
              <a name="Fats">Fats</a>
              <a name="Proteins">Proteins</a>
            </div>
          </div>
          
          <p id="macro_benefits" class="pt-0"></p>
      <div id="title2" style ="display:none">
          <div class="entry-content editor-content">
            <h3>Where can you help your children get this nutrition?</h3>
              <p id="macro_sources" style="height: 100px;">Click the button on the left</p>
          </div>
          <div class="row col-9" id="food-icons" style="display: none; justify-content: space-between; ">
            {% for i in "1234" %}
            <a id ="link_recipes{{ i }}" style="box-shadow: none;" >
              <img id="food-icon{{ i }}" class="food-icon" src="{% static 'CoreApp/assets/images/icons/' %}{% if i == 1 %}carrot.png{% elif i == 2 %}eggs.png{% else %}cauliflower.png{% endif %}" alt="vegetable icon" style="width: 50px; height: 50;">
              <p id="food-name{{ i }}" style="border-bottom: none;"></p>
            </a>
            {% endfor %}
          </div>
      </div>
      </div><!-- End row information -->

  </div>
</div>


  <div class="container">
    <hr class="mb-2">
      <div class="cta bg-image pt-3 pb-3 mb-3" style="background-color:#d2efd5;background-position: center right;">
        <div class="row justify-content-center">
            <div class="col-sm-10 col-md-8 col-lg-8">
                <div class="cta-text text-center">
                    <h3 class="cta-title"> Would you like to know more about Micronutrients? </h3><!-- End .cta-title -->
                    <p class="cta-desc">Discover Micronutrients that are essential to children's physical and cognitive development<p> 
                    </p><!-- End .cta-desc -->
                    <a href="{% url "CoreApp:micronutrients" %}" class="btn btn-primary btn-rounded"><span>Explore Micronutrients</span><i class="icon-long-arrow-right"></i></a>
                </div><!-- End .cta-text -->
            </div><!-- End .col-sm-10 col-md-8 col-lg-6 -->
        </div><!-- End .row -->
      </div><!-- End .cta -->
    </hr>
  </div>

</div>

<script>
  $(document).ready(function () {
    //var tagcloud = 
    $('#tagcloud a').on('click', function (e) {
        var tagChoice = $(this).attr('name'); // Get selected value

        if (tagChoice === 'nan') {
            return; // Do nothing and exit the function
        };
        // console.log(tagChoice)
        // AJAX call
        $.ajax({
            type: "POST",
            url: "{% url 'CoreApp:macronutrients' %}", 
            data: {'selected_tag': tagChoice,
                    'csrfmiddlewaretoken': '{{csrf_token}}'
                  },
            dataType: 'json',
            success: function (response) {
                // Update with the received JSON data
                console.log(response);
                if(response.status == 'not found'){
                    $('#macro_benefits').empty();
                    $('#macro_sources').empty();
                } else {
                $('#macro_benefits').text(response.benefits);
                $('#macro_sources').text(response.sources);
                $('#food-icons').show();
                $('#arrow-icon').hide();
                $('#title2').show();

                for (var i = 1; i <= 4; i++) {
                  var imageSource = response["image" + i];
                  var imageName = imageSource.split('/').pop().split('.')[0];
                  imageName_capital = imageName.charAt(0).toUpperCase() + imageName.slice(1);
                  
                  // Set image source and name
                  $('#food-icon' + i).attr('src', imageSource).hide().fadeIn();
                  $('#food-name' + i).text(imageName_capital).hide().fadeIn().css('text-align', 'center');
                  $('#link_recipes' + i).attr('href', "{% url "CoreApp:recipes" %}?ingredient="+ imageName);
                }

                }
            },
            error: function (request, status, error) {
                console.log(request.status + ": " + request.responseText);
            }
            
        });
    });
  });
</script>
{% endblock main_content %}

Apps/CoreApp/templates/CoreApp/Nutrition_Analysis.html
{% extends "CoreApp/base.html" %}
{% load static %}


{% block title_block %}
    
{% endblock title_block %}





{% block main_content %}

<div class="container">
    <div class="page-header" style=" background-color:#d2efd5; text-align: center;">
        <div class="container">
            <h1 class="page-title col-lg-10 mx-auto" style="font-size: 24px;text-align: center;">Nutrition Analyzer<span>{{sub_title}}</span></h1>
        </div><!-- End .container -->
</div>

<nav aria-label="breadcrumb" class="breadcrumb-nav border-0 mb-0">
    <div class="container">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url "CoreApp:index" %}">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Nutrition Analyzer</li>
        </ol>
    </div><!-- End .container -->
</nav><!-- End .breadcrumb-nav -->

<div class="page-content">
    <div class="checkout">
        <div class="container">
        {% include "CoreApp/components/recipe_analysis.html" %}
        </div>
    </div>
</div>



<div class="container">
    <div class="cta cta-border mb-5">
        <div class="row justify-content-center">
            <div class="col-md-11 col-xl-10">
                <div class="cta-content">
                    <div class="cta-heading">
                        <h3 class="cta-title text-center">Curious about your child's nutritional needs?</h3><!-- End .cta-title -->
                    </div><!-- End .cta-heading -->
                    
                    <div class="cta-text">
                        <p> After analyzing their meal with our Nutrition Analyzer, head over to Australian Nutrition Age-Based Guidelines for personalized recommendations. View Guidelines to ensure your child's diet is perfectly balanced for their growth and development!  </p>
                    </div><!-- End .cta-text -->
                    <a href="{% url "CoreApp:US21" %}" class="btn btn-primary btn-rounded"><span>Nutrition Guidelines</span><i class="icon-long-arrow-right"></i></a>
                </div><!-- End .cta-content -->
            </div><!-- End .col-xl-7 -->
        </div><!-- End .row -->
    </div><!-- End .cta -->
 
</div>

{% endblock main_content %}


{% block more_script %}
<script>
    $(document).ready(function () {
        $('#recipe, #intake').on('input', function (e) {
            var recipeChoice = $('#recipe').val(); // Get selected value
            var recipeIntake = $('#intake').val(); // Get selected value

            if (recipeChoice === 'nan') {
                return; // Do nothing and exit the function
            };
            // AJAX call
            $.ajax({
                type: "POST",
                url: "{% url 'CoreApp:guest_tracker' %}", 
                data: {'selected_recipe': recipeChoice,
                        'recipe_intake': recipeIntake,
                        'csrfmiddlewaretoken': '{{csrf_token}}'
                        },
                dataType: 'json',
                success: function (response) {
                    // Update with the received JSON data
                    //console.log(response);
                    if(response.status == 'not found'){
                        $('#recipe_description').empty();
                    } else {
                    $('#recipe_description').text(response.recipe_instructions);
                    $('.table-summary tbody').empty().append(
                        '<tr><td>Calories:</td><td>' + response.calories_intake+ 'Kcal'+
                        '<tr><td>Total Fat:</td><td>' + response.fat_total_g_intake+ 'g'+
                        '<tr><td>Saturated Fat:</td><td>' + response.fat_saturated_g_intake+ 'g'+
                        '<tr><td>Carbohydrates:</td><td>' + response.carbohydrates_total_g_intake+ 'g'+
                        '<tr><td>Protein: </td><td>' + response.protein_g_intake+ 'g'+
                        '<tr><td>Fiber:</td><td>' + response.fiber_g_intake+ 'g'
                    );
                    }
                },
                error: function (request, status, error) {
                    console.log(request.status + ": " + request.responseText);
                }
            });
        });
    });
</script>
{% endblock more_script %}

Apps/CoreApp/templates/CoreApp/coming_soon.html
{% extends "CoreApp/base.html" %}
{% load static %}


{% block title_block %}
{% endblock title_block %}





{% block main_content %}
<div class="page-content pb-3">
    <div class="soon-content-wrapper text-center" style="margin: 0 auto; max-width: 600px;">
        <!-- <img src="CoreApp/assets/images/logo-icon.png" alt="Logo" class="soon-logo mx-auto"> -->
        <h1 class="soon-title">Coming Soon</h1><!-- End .soon-title -->
        <div class="coming-countdown countdown-separator is-countdown"><span class="countdown-row countdown-show4"><span class="countdown-section"><span class="countdown-amount">00</span><span class="countdown-period">Days</span></span><span class="countdown-section"><span class="countdown-amount">00</span><span class="countdown-period">Hours</span></span><span class="countdown-section"><span class="countdown-amount">00</span><span class="countdown-period">Minutes</span></span><span class="countdown-section"><span class="countdown-amount">00</span><span class="countdown-period">Seconds</span></span></span></div><!-- End .coming-countdown -->
        <hr class="mt-2 mb-3 mt-md-3">
        <p>We are currently working on an awesome new site. Stay tuned for more information.
            Subscribe to our newsletter to stay updated on our progress.</p>
    </div>
</div>
    
</div>    
   

{% endblock main_content %}