Apps/V2CoreApp/urls.py
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required
from .views import RecipeDetailView, RecipeListView
from . import views


app_name = 'V2CoreApp'


urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
    path('obesity-overweight-children/', views.US11View.as_view(), name='US11'),
    path('food-additives/', views.US13View.as_view(), name='US13'),
    path('nutrition-guideline/', views.US21View.as_view(), name='US21'),
    path('US22/', views.US22View.as_view(), name='US22'),
    path('tracker-reminder/', views.ReminderView.as_view(), name='US23'),
    path('recipe-nutrition-analysis/', views.GuestTrackerView.as_view(), name='guest_tracker'),
    path('about-us/', views.AboutUsView.as_view(), name='about'),
    path('dash/', views.US11DashboardView.as_view(), name='dash'),
    path('profile-dashboard/', views.US121View.as_view(), name='US121'),
    path('coming-soon/', views.ComingView.as_view(), name='coming'),
    path('macronutrients-children/', views.MacronutrientsView.as_view(), name='macronutrients'),
    path('micronutrients-children/', views.MicronutrientsView.as_view(), name='micronutrients'),
    # path('recipe/', views.RecipeView.as_view(), name='recipe'),
    path('recipes/', views.RecipeListView.as_view(), name='recipes'),
    path("healthy-recipes/<slug:slug>/", RecipeDetailView.as_view(), name="recipe-detail"),
    path('veggie-insights/', views.VeggiView.as_view(), name='Veggi'),
    path('outer-recipe-analysis/', views.OuterRecipeAnalysisView.as_view(), name='outer_recipe_analysis'),
    # import data views
    path('data/', views.ImportDataView.as_view(), name='import_data'),
    path('rr/', views.LoadRecipesDataView.as_view()),
    # /data/?file_name=pb_who_bmi.csv&model_name=PB_WHO_BMI
    
    
]

SunSmart/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    #path("admin/", admin.site.urls),
    path("", include('Apps.CoreApp.urls')),
    #path("user/", include('Apps.UserAuthentication.urls')),
    path("iteration1/", include('Apps.V1CoreApp.urls')),
    path("iteration2/", include('Apps.V2CoreApp.urls'))
]

Apps/V2CoreApp/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
import numpy

GENDER_TYPE = [
    ("M", "Male"),
    ("F", "Female"),
    ("P", "Persons")
]

AGE_GROUP = [
    ("A", "2-3"),
    ("B", "4-8"),
    ("C", "9-13")
]


class PB_AU_CONCERN_V2(models.Model):
    concern = models.CharField(max_length=150, null=True, blank=True)
    gender = models.CharField(max_length=20, choices = GENDER_TYPE, null=True, blank=True)
    age_group = models.CharField(max_length=20, choices = AGE_GROUP, null=True, blank=True)
    percentage = models.FloatField(null=True, blank=True)
    
class PB_AU_VEGGIE_V2(models.Model):
    year = models.IntegerField( null=True, blank=True)
    concern = models.CharField(max_length=150, null=True, blank=True)
    concern_label = models.CharField(max_length=150, null=True, blank=True)
    gender = models.CharField(max_length=20, choices = GENDER_TYPE, null=True, blank=True)
    age_group = models.CharField(max_length=20, choices = AGE_GROUP, null=True, blank=True)
    percentage = models.FloatField(null=True, blank=True)
    margin_error = models.FloatField(null=True, blank=True)    
    
class PB_WHO_BMI_V2(models.Model):
    bmi = models.CharField(max_length=150, null=True, blank=True)
    year = models.IntegerField( null=True, blank=True)
    gender = models.CharField(max_length=20, choices = GENDER_TYPE, null=True, blank=True)
    crude_estimate = models.FloatField(null=True, blank=True)
    

class PAGE_VIEW_V2(models.Model):
    path = models.CharField(max_length=1001, unique=True)
    views = models.IntegerField(default=1)
    
class HEALTH_TAG_V2(models.Model):
    tag = models.CharField(max_length=150, null=True, blank=True)


class DIET_LABEL_V2(models.Model):
    label = models.CharField(max_length=150, null=True, blank=True)


class MEAL_TYPE_V2(models.Model):
    type = models.CharField(max_length=150, null=True, blank=True)


class INGREDIENT_V2(models.Model):
    name = models.CharField(max_length=100)
    food_category = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class NUTRIENTS_V2(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class RECIPES_V2(models.Model):
    name = models.CharField(max_length=500, null=True, blank=True)
    description = models.TextField( null=True, blank=True)
    url = models.URLField(max_length=1000)
    total_time = models.CharField(max_length=5, null=True, blank=True)
    serving = models.CharField(max_length=5, null=True, blank=True)
    
    health_tag = models.ManyToManyField(HEALTH_TAG_V2, related_name='recipes_h_v2')
    diet_label = models.ManyToManyField(DIET_LABEL_V2, related_name='recipes_d_v2')
    meal = models.ManyToManyField(MEAL_TYPE_V2, related_name='recipes_m')
    ingredients = models.ManyToManyField(INGREDIENT_V2, through='RECIPE_INGREDIENT_V2')
    nutrients = models.ManyToManyField(NUTRIENTS_V2, through='RECIPE_NUTRIENTS_V2')
    
    slug = models.SlugField(max_length=500, unique=True, null=True, blank=True)
    page_view = models.OneToOneField(PAGE_VIEW_V2, on_delete=models.CASCADE, null=True, blank=True)
    created_on = models.DateTimeField(auto_now_add=True, editable=False)
    

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.slug = slugify(self.name)
        if update_fields is not None and "name" in update_fields:
            update_fields = {"slug"}.union(update_fields)
                          
        # Create or update associated PAGE_VIEW
        if not self.page_view_id:
            page_view, _ = PAGE_VIEW_V2.objects.get_or_create(path=self.get_absolute_url())
            self.page_view = page_view
            
        super().save(
            force_insert=force_insert,
            force_update=force_update,
            using=using,
            update_fields=update_fields,
        )
        
    def get_absolute_url(self):
        # return urllib.parse.unquote(reverse('CoreAPP:recipe-detail', kwargs={'slug': self.slug}))
        return reverse('V2CoreApp:recipe-detail', kwargs={'slug': self.slug})
        

class RECIPE_INGREDIENT_V2(models.Model):
    recipe = models.ForeignKey(RECIPES_V2, related_name='related_ingredients_v2', on_delete=models.CASCADE)
    ingredient = models.ForeignKey(INGREDIENT_V2, on_delete=models.CASCADE)
    quantity = models.CharField(max_length=100, null=True, blank=True)
    measure = models.CharField(max_length=50, null=True, blank=True)
    ingredient_text = models.CharField(max_length=700, null=True, blank=True)

    def __str__(self):
        return f"{self.quantity} {self.measure} of {self.ingredient.name} for {self.recipe}"
    
class RECIPE_NUTRIENTS_V2(models.Model):
    recipe = models.ForeignKey(RECIPES_V2, related_name='related_nutrients_v2', on_delete=models.CASCADE)
    nutrient = models.ForeignKey(NUTRIENTS_V2, on_delete=models.CASCADE)
    quantity = models.CharField(max_length=100, null=True, blank=True)
    measure = models.CharField(max_length=50, null=True, blank=True)


    def __str__(self):
        return f"{self.nutrient.name} : {numpy.round(float(self.quantity))} {self.measure} "
    


    

Apps/V2CoreApp/views.py
from typing import Any
from django.http.request import HttpRequest as HttpRequest
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.views import generic
from django.core.mail import send_mail
from django.core.management.utils import get_random_secret_key
from django.utils.text import slugify
from .models import *
from django.apps import apps
import os
from .utils import api_request, login_required
import pandas as pd
from django.core import serializers
import json
import requests
from django.db.models import Q
from functools import reduce
from operator import or_


class CustomLoginRequiredMixin:
    def dispatch(self, request, *args, **kwargs):
        if 'user_id' not in request.session:
            # Redirect to the login page
            messages.add_message(self.request, messages.INFO, 'You need to login to access the content')
            # Store the requested URL in the session
            request.session['next'] = request.get_full_path()
            return redirect('V2CoreApp:login_or_register')
        return super().dispatch(request, *args, **kwargs)
    
    
class HomeView(generic.TemplateView):
    template_name = 'V2CoreApp/index.html'
    
    def import_data(self):
        filename = "C:/Users/Parisa/Downloads/tb_concern.csv"
        df = pd.read_csv(filename)
        for index, row in df.iterrows():
            temp_row = PB_AU_CONCERN_V2(concern=row['concern'], 
                                        gender=row['gender'],
                                        age_group=row['age_group'],
                                        percentage=row['percentage'])
            
            temp_row.save()
    
    def import_bmi_data(self):
        filename = "C:/Users/Parisa/Downloads/pb_who_bmi.csv"
        df = pd.read_csv(filename)
        for index, row in df.iterrows():
            temp_row = PB_WHO_BMI_V2(bmi=row['bmi_code'], 
                                        gender=row['gender'],
                                        year=row['year'],
                                        crude_estimate=row['crude_estimate'])
            
            temp_row.save()
        
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        
        # self.import_bmi_data()
            
        return super().get_context_data(**kwargs)

#overweight info page    
class US11View(generic.TemplateView):
    template_name = 'V2CoreApp/overweight.html'
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        super().get_context_data(**kwargs)
        
        # query from table
        all_data = PB_AU_CONCERN_V2.objects.all()
        serialized_data = serializers.serialize('json', all_data)
        
        
        all_data_bmi = PB_WHO_BMI_V2.objects.all()
        serialized_data_bmi = serializers.serialize('json', all_data_bmi)
    
        
        new_context = {'main_title': 'Obesity and Overweight among Children',
                    #    'sub_title': 'Obesity and Overweight among Children',
                       'page_name': 'Obesity and Overweight',
                       'json_data': serialized_data,
                       'json_data_bmi': serialized_data_bmi}
        
        return new_context
        

class US11DashboardView(generic.TemplateView):
    template_name = 'V2CoreApp/us11_dashboard.html'
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        super().get_context_data(**kwargs)
        
        # query from table
        all_data = PB_AU_CONCERN_V2.objects.all()
        serialized_data = serializers.serialize('json', all_data)
        
        
        all_data_bmi = PB_WHO_BMI_V2.objects.all()
        serialized_data_bmi = serializers.serialize('json', all_data_bmi)
    
        
        new_context = {'main_title': 'Checkout',
                       'sub_title': 'Shop',
                       'page_name': 'US11',
                       'json_data': serialized_data,
                       'json_data_bmi': serialized_data_bmi}
        
        return new_context
 
    
class US121View(generic.TemplateView):
    template_name = 'V2CoreApp/us121.html'


class US13View(generic.TemplateView):
    template_name = 'V2CoreApp/additive.html'
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        super().get_context_data(**kwargs)
        
        
    
        
        new_context = {'main_title': 'Understanding Food Additives: Uses, Reactions, and Safety',
                       'sub_title': '',
                       'page_name': 'Understanding Food Additives'
                       }
        
        return new_context

#nutrition-guideline
class US21View(generic.TemplateView):
    template_name = 'V2CoreApp/nutrition-guideline.html'
    data = ""
    
    #read json guideline
    def setup(self, request, *args, **kwargs):
        file_address = os.path.join('Data Sources', 'guideline.json')
        with open(file_address, 'r') as f:
            # JSON to dictionary
            self.data = json.load(f)
            
        return super().setup(request, *args, **kwargs)
    
    #search age
    def post(self, request):
        selected_age_range = request.POST.get('selected_age_range')  
        print(selected_age_range) 
        # find the recipe in recipes
        for r in self.data:
            if r.get('age_range') == selected_age_range:
                age_range = r
                print(age_range)
                break
            else:
                age_range = {'status': 'not found'}
                
        return JsonResponse(age_range)            
              
                
class US22View(generic.TemplateView):
    template_name = 'V2CoreApp/us22.html'

#Reminder page
class ReminderView(generic.TemplateView):
    template_name = 'V2CoreApp/reminder_main.html'
    
    def post(self, request):
        email = request.POST.get('email', None)
        date = request.POST.get('date', None)
        meal = request.POST.get('meal', None)
        
        # send sign-in data to authentication API
        api_url = 'http://juniorjoy.site/api/reminder/set-ses-reminder'
        
        data = {'email': email,
                'date': date,
                'meal': meal
        }
        response = api_request(url=api_url, parameters=data, request_type='POST')    
       
        messages.add_message(self.request, messages.SUCCESS, 'The reminder has been set successfully  ')
        
        return redirect('V2CoreApp:US23')
        
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        super().get_context_data(**kwargs)
  
        new_context = {'main_title': 'Reminder',
                       'sub_title': '',
                       'page_name': 'Reminder'
        }
        
        return new_context


class AboutUsView(generic.TemplateView):
    template_name = 'V2CoreApp/about_us.html'


# class GuestTrackerView(CustomLoginRequiredMixin, generic.TemplateView):
class GuestTrackerView(generic.TemplateView):
    template_name = 'V2CoreApp/Nutrition_Analysis.html'
    recipes = None
    headers = {
                "Content-Type": "application/json"
                }
    
    def setup(self, request, *args, **kwargs):
        file_address = os.path.join('Data Sources', 'recipes.json')
        with open(file_address, 'r') as f:
            # JSON to dictionary
            self.recipes = json.load(f)
            
        return super().setup(request, *args, **kwargs)
    
    def post(self, request):
        
        if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            selected_recipe = request.POST.get('selected_recipe')
            recipe_intake = request.POST.get('recipe_intake')
                            
            # find the recipe in recipes
            for r in self.recipes:
                if r.get('recipe_name') == selected_recipe:
                    recipe = r
                    break
                else:
                    recipe = {'status': 'not found'}
                    
            # send sign-in data to authentication API
            api_url = 'https://juniorjoy.site/api/api/calcucalories'
            data = {
                "query": recipe['recipe_ingredients'],
                "intake": recipe_intake,
                "serving": recipe['recipe_servings']
            }
                        
            response = requests.get(api_url, headers=self.headers, json=data)
            
            if response.status_code == 200:
                # Append the calorie information to the recipe
                recipe['nutrient_info'] = response.json()            
                response_data = response.json()

                recipe['calories_intake'] = response_data['calories_intake']
                recipe['serving_size_g_intake'] = response_data['serving_size_g_intake']
                recipe['fat_total_g_intake'] = response_data['fat_total_g_intake']
                recipe['fat_saturated_g_intake'] = response_data['fat_saturated_g_intake']
                recipe['protein_g_intake'] = response_data['protein_g_intake']
                # recipe['sodium_mg_intake'] = response_data['sodium_mg_intake']
                # recipe['potassium_mg_intake'] = response_data['potassium_mg_intake']
                # recipe['cholesterol_mg_intake'] = response_data['cholesterol_mg_intake']
                recipe['carbohydrates_total_g_intake'] = response_data['carbohydrates_total_g_intake']
                recipe['fiber_g_intake'] = response_data['fiber_g_intake']
                recipe['sugar_g_intake'] = response_data['sugar_g_intake']

            else:
                # Handle API error
                recipe['nutrient_info'] = {'error': 'Failed to retrieve calorie information'}
                    
            return JsonResponse(recipe)
        
        # Not AJAX request
        else:

Apps/V2CoreApp/templates/V2CoreApp/nutrition-guideline.html
{% extends "V2CoreApp/base.html" %}
{% load static %}


{% block title_block %}
    
{% endblock title_block %}





{% block main_content %}


<div class="container">
    <div class="page-header" style=" background-color:#d2efd5; text-align: center;">
        <div class="container">
            <h1 class="page-title col-lg-10 mx-auto" style="font-size: 24px;text-align: center;">Nutrition Guideline<span>{{sub_title}}</span></h1>
        </div><!-- End .container -->
</div>




        <nav aria-label="breadcrumb" class="breadcrumb-nav border-0 mb-0">
            <div class="container">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url "V2CoreApp:index" %}">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Nutrition Guideline</li>
                </ol>
            </div><!-- End .container -->
        </nav><!-- End .breadcrumb-nav -->
    
        <div class="page-content">
            <div class="checkout">
                <div class="container">
                        <div class="row">
                            <div class="col-lg-7">
                                <h2 class="checkout-title">Australian Nutrition Guideline for Children</h2><!-- End .checkout-title -->
                                <p>Choose your child's age from menue and view the Australian Nutrition Guideline.</p><!-- End .checkout-title -->
                                <div class="row">
                                    <div class="col-sm-4">
                                        <label>Age Group</label>
                                        <div class="w3-content" style="max-width:2000px;margin-top:15px"></div>
                                        <div class="select-custom">
                                            <select name="selected_age_range" id="age_range" class="form-control">
                                                <option value="Ages 2 to 4">Ages 2 to 4</option>
                                                <option value="Ages 5 to 8">Ages 5 to 8</option>
                                                <option value="Ages 9 to 13">Ages 9 to 13</option>
                                            </select>
                                        </div><!-- End .select-custom -->
                                    </div><!-- End .col-sm-6 -->
                                </div>
                                <div class="row mt-5" style="display: none;">
                                    <div class="summary" style="min-width: -webkit-fill-available;">
                                        <h3 class="summary-title">Recipe Description</h3>
                                        <p id="recipe_description" style="padding-bottom: 1.7rem"></p>
                                    </div><!-- End .summary -->
                                </div>
                            </div>
                            <aside class="col-lg-4">
                                <div class="summary">
                                    <h3 class="summary-title">Nutrition Guideline</h3>
                                    

                                    <table class="table table-summary mt-0">
                                        <thead>
                                            <tr>
                                                <th>Nutrition</th>
                                                <th>Amount</th>
                                            </tr>
                                        </thead>

                                        <tbody>
                                            <tr>
                                                <td>Calories:</td>
                                                <td></td>
                                            </tr>

                                            <tr>
                                                <td>Protein:</td>
                                                <td></td>
                                            </tr>
                                            <tr>
                                                <td>Dairy:</td>
                                                <td></td>
                                            </tr><!-- End .summary-subtotal -->
                                            <tr>
                                                <td>Grains:</td>
                                                <td></td>
                                            </tr>
                                            <tr>
                                                <td>Fruits:</td>
                                                <td></td>
                                            </tr>
                                            <tr>
                                                <td>Vegetables:</td>
                                                <td></td>
                                            </tr>
                                            <!-- End .summary-total -->


                                        </tbody>
                                    </table><!-- End .table table-summary -->

                                </div><!-- End .summary -->
                            </aside><!-- End .col-lg-3 -->
                        </div><!-- End .row -->
                </div><!-- End .container -->
            </div><!-- End .checkout -->

            <!-- section4 -->
            <div class="w3-content" style="max-width:2000px;margin-top:30px"></div>
<div class="container">
    <div class="cta cta-border mb-5">
        <div class="row justify-content-center">
            <div class="col-md-11 col-xl-10">
                <div class="cta-content">
                    <div class="cta-heading">
                        <h3 class="cta-title text-center">Wondering if your child's meal hits the mark?</h3><!-- End .cta-title -->
                    </div><!-- End .cta-heading -->
                    
                    <div class="cta-text">
                        <p>Let our <strong>Nutrition Analysis tool</strong> be your guide! Enter your recipe and the portion size your child enjoyed, and get a personalized breakdown of its nutritional value. Compare against age-based guidelines for tailored insights. Click now to ensure your child gets the nutrients they need! </p>
                    </div><!-- End .cta-text -->
                    <a href="{% url "V2CoreApp:guest_tracker" %}" class="btn btn-primary btn-rounded"><span>Nutrition Analyzer</span><i class="icon-long-arrow-right"></i></a>
                </div><!-- End .cta-content -->
            </div><!-- End .col-xl-7 -->
        </div><!-- End .row -->
    </div><!-- End .cta -->
 
</div>


        </div>

{% endblock main_content %}


{% block more_script %}
<script>
    $(document).ready(function () {
        $('#age_range').on('input', function (e) {
            var ageChoice = $('#age_range').val(); // Get selected value

            if (ageChoice === 'nan') {
                return; // Do nothing and exit the function
            };
            
         
            // AJAX call
            $.ajax({
                type: "POST",
                url: "{% url 'V2CoreApp:US21' %}", 
                data: {'selected_age_range': ageChoice,
                        'csrfmiddlewaretoken': '{{csrf_token}}'
                        },
                dataType: 'json',
                success: function (response) {
                    // Update with the received JSON data
                    //console.log(response);
                    if(response.status == 'not found'){
                        $('#selected_age_range').empty();
                    } else {
                    
                    $('.table-summary tbody').empty().append(
                        '<tr><td>Calories:</td><td>' + response.daily_guidelines.calories +
                        '<tr><td>Protein:</td><td>' + response.daily_guidelines.protein+
                        '<tr><td>Dairy:</td><td>' + response.daily_guidelines.dairy+
                        '<tr><td>Grains:</td><td>' + response.daily_guidelines.grains+
                        '<tr><td>Fruits: </td><td>' + response.daily_guidelines.fruits+
                        '<tr><td>Vegetables:</td><td>' + response.daily_guidelines.vegetables
                    );
                    }
                },
                error: function (request, status, error) {
                    console.log(request.status + ": " + request.responseText);
                }
            });
        
        });
        
    });
</script>
{% endblock more_script %}

Apps/V2CoreApp/templates/V2CoreApp/outer_recipe_analysis.html
{% extends "V2CoreApp/base.html" %}
{% load static %}


{% block title_block %}
    
{% endblock title_block %}





{% block main_content %}

<div class="container">
    <div class="page-header" style=" background-color:#d2efd5; text-align: center;">
        <div class="container">
            <h1 class="page-title col-lg-10 mx-auto" style="font-size: 24px;text-align: center;">Recipe Analyzer<span>{{sub_title}}</span></h1>
        </div><!-- End .container -->
</div>

<nav aria-label="breadcrumb" class="breadcrumb-nav border-0 mb-0">
    <div class="container">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url "V2CoreApp:index" %}">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Recipe Analyzer</li>
        </ol>
    </div><!-- End .container -->
</nav><!-- End .breadcrumb-nav -->


<div class="row">
    <div class="col-lg-8">
        <h2 class="checkout-title">Recipe Nutrition Analysis</h2><!-- End .checkout-title -->
        <div class="row">
            <div class="col-sm-12 mx-auto">
                <p>Enter a list of ingredients for what you are cooking, like <span class="example">"1 cup rice, 10 oz chickpeas"</span>, etc.<br></p>
                <div class="w3-content" style="max-width:2000px;margin-top:15px"></div>
                <form id="demoAnalysisForm" method ="post">{% csrf_token %}
                    <p>
                      <textarea name="custom_recipe" id="demoAnalysis" cols="30" rows="10" class="form-control"></textarea>
                    </p>
                    <div class="w3-content" style="max-width:2000px;margin-top:30px"></div>
                    <div style="text-align: center;">
                            <button  type="submit" class="btn btn-primary btn-rounded">Analyze</button>
                    </div>
                    <div class="w3-content" style="max-width:2000px;margin-top:30px"></div>
                    
                    
                    <div class="err-result">
                        <p class="addition-e">Note: We cannot calculate the nutrition for some ingredients. Please check the ingredient spelling and the quantity.
                        </p>
                    </div>
                    <div class="demo-result">
                        <div class="col-md-12">

                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <aside class="col-lg-4">
        <div class="summary">
            <h3 class="summary-title">Nutrition Analysis</h3>
            <p id="food_description" style="border-bottom: .1rem solid #ebebeb; padding-bottom: 1.7rem"></p>

            <table class="table table-summary mt-3">
                <thead>
                    <tr>
                        <th>Nutrition</th>
                        <th>Amount</th>
                    </tr>
                </thead>

                <tbody>
                    <tr>
                        <td>Calories:</td>
                        <td>{{api_data.calories_intake}}Kcal</td>
                    </tr>

                    <tr>
                        <td>Total Fat:</td>
                        <td>{{api_data.fat_total_g_intake}}g</td>
                    </tr>
                    <tr>
                        <td>Saturated Fat:</td>
                        <td>{{api_data.fat_saturated_g_intake}}g</td>
                    </tr><!-- End .summary-subtotal -->
                    <tr>
                        <td>Carbohydrates:</td>
                        <td>{{api_data.carbohydrates_total_g_intake}}g</td>
                    </tr>
                    <tr>
                        <td>Fiber:</td>
                        <td>{{api_data.fiber_g_intake}}g</td>
                    </tr>
                    <tr>
                        <td>Sugar:</td>
                        <td>{{api_data.sugar_g_intake}}g</td>
                    </tr><!-- End .summary-total -->
                </tbody>
            </table><!-- End .table table-summary -->

        </div><!-- End .summary -->
    </aside><!-- End .col-lg-3 -->
</div><!-- End .row -->






{% endblock main_content %}



{% block more_script %}
<script>
    document.getElementById('newRecipeBtn').addEventListener('click', function() {
        document.getElementById('demoAnalysis').value = ''; // Clear the textarea
      });
</script>
{% endblock more_script %}